# Generated by Django 4.2.3 on 2023-07-18 13:28

import Overview.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=Overview.models.path_and_rename, verbose_name='Image')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
            ],
            options={
                'verbose_name': 'overview',
                'verbose_name_plural': 'overview',
                'db_table': 'overview',
            },
        ),
    ]
