# Generated by Django 4.2.3 on 2023-07-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, verbose_name='Name')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
            ],
            options={
                'verbose_name': 'visiting',
                'verbose_name_plural': 'visiting',
                'db_table': 'visiting',
            },
        ),
    ]
