# Generated by Django 4.2.3 on 2023-07-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transit',
            name='type',
            field=models.CharField(choices=[('elevator', 'Elevator'), ('circle-line', 'CircleLine'), ('downtown-line', 'DowntownLine'), ('bus', 'Bus')], max_length=255, verbose_name='Type'),
        ),
    ]
