# Generated by Django 4.2.3 on 2023-07-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('cover', models.ImageField(blank=True, default=None, null=True, upload_to='images/', verbose_name='Cover')),
                ('type', models.CharField(choices=[('news', 'News'), ('facilities', 'Facilities'), ('club', 'Club')], max_length=255, verbose_name='Type')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
            ],
            options={
                'verbose_name': 'Magazine',
                'verbose_name_plural': 'Magazine',
                'db_table': 'magazine',
            },
        ),
    ]
