# Generated by Django 4.2.3 on 2023-07-18 12:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Magazine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Content'),
        ),
    ]
