# Generated by Django 4.2.3 on 2023-07-18 12:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Magazine', '0002_alter_magazine_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content'),
        ),
    ]
