# Generated by Django 4.2.3 on 2023-07-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magazine', '0003_alter_magazine_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='type',
            field=models.CharField(choices=[('news', 'News'), ('facilities', 'Facilities'), ('clubs', 'Clubs')], max_length=255, verbose_name='Type'),
        ),
    ]
