# Generated by Django 4.2.3 on 2023-07-18 12:51

import Magazine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magazine', '0004_alter_magazine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='cover',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=Magazine.models.path_and_rename, verbose_name='Cover'),
        ),
    ]
